In [7]:
a = [10,20,30,31,21,22]

def find_index(seq, value):
    """
    finds the index of value in seq
    returns -1 if not found
    """
    """
    for i in range(len(seq)):
        if seq[i] == value:
            return i
    """
    for i,data  in enumerate(seq):
        if data == value:
            return i
    return -1

print(find_index(a, 20))
print(find_index(a, 22))
print(find_index(a, 23))
    

1
5
-1


In [9]:
s1 = 'abcdABq'
s2 = 'PQERDF'

for i in range(len(s1)):
    print(s1[i], s2[i])

a P
b Q
c E
d R
A D
B F


IndexError: string index out of range

In [10]:
s1 = 'abcdABq'
s2 = 'PQERDF'

for i in zip(s1,s2):
    print(i)

('a', 'P')
('b', 'Q')
('c', 'E')
('d', 'R')
('A', 'D')
('B', 'F')


In [15]:
def is_equal(seq1, seq2):
    
    if len(seq1) != len(seq2):
        return False

    for d1,d2 in zip(seq1, seq2):
        if d1 != d2:
            return False
        
    return True

print(is_equal( [10,20], [10,20] ) )
print(is_equal( [10,20], [10,30] ) )
print(is_equal( [10,20], [10,20,30] ) )
print(is_equal( [10,20], ['a','b'] ) )

True
False
False
False


In [18]:

def is_pallindrome(word):
    for i in range(len(word)//2):
        if word[i] != word[-(i + 1)]:
            return False
    return True
"""
with open(...) as f:
    for line in f:
        for word in line.split():
            count+= is_pallindrome(word)
"""
print(is_pallindrome('abc'))
print(is_pallindrome('abcba'))
print(is_pallindrome('abcbaa'))

False
True
False


In [23]:
def second_maximum(d1):
    if(len(d1) > 2 ):
        if d1[0] > d1[1]:
            f_max = d1[0]
            s_max = d1[1]
        else:
            f_max = d1[1]
            s_max = d1[0]
        for i in range(2,len(d1)):
            if d1[i] > f_max:
                s_max = f_max
                f_max = d1[i]
            
            if d1[i] > s_max: 
                s_max = d1[i]
        f_s = f_max,s_max
        return f_s
    else:
        print("Enter list with atleast 3 numbers ")
print(second_maximum([10,20,30,40]))   
print(second_maximum([40,30,20,10]))    
print(second_maximum([40,20,30,10]))           

(40, 40)
(40, 30)
(40, 30)


In [ ]:
def get_max(seq):
    if len(seq) == 0:
        return None
    
    m = seq[0]
    for i in range(1, len(seq)):
        if seq[i] > m:
            m = seq[i]
    return m

In [ ]:
def is_leap_year(year):
    if year > 999 and year < 10000:
        # if year is not a multiple of 100 it can be muliple of 4
        if (year % 100 != 0 and year%4 == 0):
            return True
        #
        elif year % 400 == 0:
            return True

    return False

def is_leap_year(year):
    if year > 999 and year < 10000:
        if (year % 100 != 0 and year%4 == 0) or year % 400 == 0:
            return True

    return False

def is_leap_year(year):
    if (year > 999 and year < 10000) and ((year % 100 != 0 and year%4 == 0) or year % 400 == 0):
        return True

    return False

def is_leap_year(year):
    return (year > 999 and year < 10000) and ((year % 100 != 0 and year%4 == 0) or year % 400 == 0):


In [25]:
a = ["hello", "world" , "test" , "this" , "here" , "now" ]
value = 100

r = [(data, value) for data in a]
print(r)

dict(r)


[('hello', 100), ('world', 100), ('test', 100), ('this', 100), ('here', 100), ('now', 100)]


{'hello': 100, 'world': 100, 'test': 100, 'this': 100, 'here': 100, 'now': 100}

In [35]:
import numpy as np
a =  np.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
print(a)

import numpy as np
print(str(np.floor(a)).replace('[', '[ '))
print(np.ceil(a))
print(np.rint(a),end='')

[1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9]
[ 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  6.  7.  8.  9. 10.]